version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:22.4.0  # CircleCI Node.js image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server in background
          command: |
            npm run dev &
            
              sleep 15
            
      - run:
           name: Debug server logs
           command: tail -f server.log &
      - run:
          name: Run tests with Mochawesome
          command: npm test
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
