version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.4.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start server in background
          command: |
            npm run dev &
            sleep 10  # wait 10s to give the server time to start

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
